### ISSUE TITLE
jctl line 13 error

### ISSUE THREAD

**Issue by zenny** [phalaaxx/jail#1]
Got:

> # jctl --groups-setup
> 
>   File "/usr/sbin/jctl", line 13
>     elif args.chroot_update:
>        ^
> SyntaxError: invalid syntax

elif syntax error?! Hmmm

**Comment by phalaaxx** [comment]
A typo, sorry.
Also sorry for the delay, I didn't realize there was an open issue (I didn't really expect anyone to use this code).
